options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _APP_NAME: 'modal-fastapi-server'
  _COMMIT_SHA: '${SHORT_SHA}'
  _ENVIRONMENT: '${BRANCH_NAME}'

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "TOKEN_ID: $$TOKEN_ID"
        echo "TOKEN_SECRET: $$TOKEN_SECRET"
    secretEnv: ['TOKEN_ID', 'TOKEN_SECRET']


  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/${_APP_NAME}']
    id: 'pull-latest-image'
    allowFailure: true

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:latest', 
      '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:${_COMMIT_SHA}', 
      '--cache-from', 'gcr.io/$PROJECT_ID/${_APP_NAME}:latest', 
      '--build-arg', 'TOKEN_ID=$TOKEN_ID',
      '--build-arg', 'TOKEN_SECRET=$TOKEN_SECRET',
      '.'
    ]
    waitFor: ['pull-latest-image']
    secretEnv: ['TOKEN_ID', 'TOKEN_SECRET']


images:
  - 'gcr.io/$PROJECT_ID/${_APP_NAME}:latest'
  - 'gcr.io/$PROJECT_ID/${_APP_NAME}:${_COMMIT_SHA}'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/TOKEN_ID/versions/latest
      env: 'TOKEN_ID'
    - versionName: projects/$PROJECT_ID/secrets/TOKEN_SECRET/versions/latest
      env: 'TOKEN_SECRET'
