FROM ubuntu:latest

RUN apt-get update --fix-missing

RUN apt install -y python3 python3-dev python3-pip

RUN pip install fastapi uvicorn locust 

RUN apt-get -y install git

RUN git clone https://github.com/qolaba/deepfloyd.git


WORKDIR /deepfloyd

ENTRYPOINT python3 df.py